server:
  port: 8083
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/practice}
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:55432/orderdb}
    username: ${DB_USERNAME:practice}
    password: ${DB_PASSWORD:practice}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
internal:
  service-token: ${INTERNAL_SERVICE_TOKEN:}
